In [1]:
import torch

In [2]:
t = torch.tensor([1, 2, 3])

In [3]:
t

tensor([1, 2, 3])

In [9]:
if torch.cuda.is_available():  # 检查 CUDA 是否可用
    t_cuda = t.cuda()  # 将张量 t 移动到 CUDA 设备
    print(t.is_cuda)
    print(t_cuda.is_cuda)
else:
    print("no CUDA")

no CUDA


In [11]:
from torch import nn

module = nn.Linear(3, 4)

if torch.cuda.is_available():
    module.cuda(device=0)
    print(module.weight.is_cuda)  # True
else:
    print("no CUDA")

no CUDA


In [12]:
# 使用.to方法，将 Tensor 转移至第 0 块GPU上
t = torch.tensor([1, 2, 3])

if torch.cuda.is_available():
    t_cuda = t.to('cuda:0')
    print(t_cuda.is_cuda)
else:
    print("no CUDA")

no CUDA


In [15]:
if torch.cuda.is_available():
    # 以交叉熵损失函数为例
    criterion = torch.nn.CrossEntropyLoss(weight=torch.Tensor([1, 3]))

    # 张量 Tensor 迁移到 GPU
    inputs = torch.randn(4, 2).cuda()
    target = t.Tensor([1, 0, 0, 1]).long().cuda()

    # loss = criterion(input, target)  # 报错：计算损失函数的参数为迁移到 GPU

    # 正确：迁移损失函数
    criterion.cuda()
    loss = criterion(inputs, target)
    print(criterion._buffers)

In [16]:
# 指定默认使用GPU "cuda:0"
with torch.cuda.device(0):
    # 在 GPU 上构建Tensor
    a = torch.cuda.FloatTensor(2, 3)

    # 将 Tensor 转移至 GPU
    b = torch.FloatTensor(2, 3).cuda()

    print(a.get_divice)
    print(b.get_divice)

    c = a + b
    print(c.get_divice)

RuntimeError: PyTorch was compiled without CUDA support

In [18]:
torch.set_default_tensor_type('torch.cuda.FloatTensor')  # 指定默认 Tensor 的类型为GPU上的FloatTensor
a = torch.ones(2, 3)
print(a.is_cuda)

torch.set_default_tensor_type('torch.FloatTensor')  # 恢复默认

TypeError: type torch.cuda.FloatTensor not available. Torch not compiled with CUDA enabled.

In [19]:
# import os
# os.environ['CUDA_VISIBLE_DEVICES'] = '0'

In [ ]:
# %env CUDA_VISIBLE_DEVICES=0

In [22]:
# 【推荐】如果用户具有 GPU 设备，那么使用GPU，否则使用CPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cpu


In [23]:
device

device(type='cpu')

In [26]:
x = torch.randn(2, 3)
x_to = x.to(device)
print(x_to.device)

cpu


In [27]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
x_cpu = torch.empty(2, device='cpu')
print(x_cpu, x_cpu.is_cuda)
x_gpu = torch.empty(2, device=device)
print(x_gpu, x_gpu.is_cuda)

tensor([0., 0.]) False
tensor([0., 0.]) False


In [28]:
# new_*() : 保留原 Tensor 的设备属性
y_cpu = x_cpu.new_full((3, 4), 9)  # new_full : 用 9 填充形状 [3, 4] 的张量
print(y_cpu, y_cpu.is_cuda)
y_gpu = x_gpu.new_zeros(3, 4)  # new_zeros : 填充 0
print(y_gpu, y_gpu.is_cuda)

tensor([[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]]) False
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]) False


In [29]:
# 使用ones_like或zeros_like可以创建与原Tensor大小类别均相同的新Tensor
z_cpu = torch.ones_like(x_cpu)  # 大小相同，设备相同
print(z_cpu, z_cpu.is_cuda)

z_gpu = torch.zeros_like(x_gpu)  # 大小相同，设备相同
print(z_gpu, z_gpu.is_cuda)

tensor([1., 1.]) False
tensor([0., 0.]) False
